task:
  name: Docker_Build_Push
  only_if: true
  
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 8
    memory: 16G
  
  # Environment variables:
  env:
      DOCKER_USERNAME: lumine
      DOCKER_PASSWORD: 51TB3owcp36kTtaYozoBFwpN+ud1GEp5/uSThgQgcaeRGHvWLbF5DH2d29HJuQ9U
      DOCKER_REGISTRY: quay.io

  # Instructions:
  Docker_Login_script: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}
  Build_Image_script: docker build -f Dockerfiles/Code-Server-Ultimate/Dockerfile -t ${DOCKER_REGISTRY}/lumine/ptero-images:code-server-ult .
  Push_Image_script: docker push ${DOCKER_REGISTRY}/lumine/ptero-images:code-server-ult
