task:
  name: Docker_Build_Push
  only_if: true
  
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 16G
 
  # Instructions:
  Docker_Login_Script: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}" ${{ secrets.DOCKER_REGISTRY_URL }}
  Image_Build_Script: docker build -f Dockerfiles/CI-Test/Dockerfile -t quay.io/lumine/ptero-images:ci-test .
  Image_Push_Script: docker push quay.io/lumine/ptero-images:ci-test
