task:
  name: Docker_Build_Push
  only_if: true
  
  compute_engine_instance:
    image_project: cirrus-images
    image: family/docker-builder
    platform: linux
    cpu: 4
    memory: 16G
  
  # Environment variables:
  env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY_URL }}

  # Instructions:
  Docker_Login_script: docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}" ${DOCKER_REGISTRY}
  Build_Image_script: docker build -f Dockerfiles/Test-CI-Egg/Dockerfile -t ${DOCKER_REGISTRY}/lumine/ptero-images:test-egg .
  Push_Image_script: docker push ${DOCKER_REGISTRY}/lumine/ptero-images:test-egg
